services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db

    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: backend-ecommerce

      MYSQL_PASSWORD: rootpassword123
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ecom-net
  backend:
    build: ./ecom-backend
    container_name: spring-backend
    environment:
      - DB_URL=jdbc:mysql://mysql-db:3306/backend-ecommerce?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword123
    depends_on:
      mysql:
          condition: service_healthy

    ports:
      - "8083:8083"
    networks:
      - ecom-net

  frontend:
    build: ./ecom-frontend
    container_name: angular-frontend
    depends_on:
      - backend
    ports:
      - "8086:80"
    networks:
      - ecom-net
networks:
  ecom-net:
    driver: bridge
volumes:
  mysql_data:
